CREATE TABLE Quiz(
	ID BIGINT AUTO_INCREMENT PRIMARY KEY,
	Name nvarchar(50) NULL
);

CREATE TABLE Question(
	ID BIGINT AUTO_INCREMENT PRIMARY KEY,
	Question nvarchar(100) NULL,
	QuizID BIGINT NOT NULL
);

CREATE TABLE Answer(
	ID BIGINT AUTO_INCREMENT PRIMARY KEY,
	Answer nvarchar(50) NULL,
	ResultChar nchar(1) NULL,
	QuestionID BIGINT NULL
);

CREATE TABLE Result(
	ID BIGINT AUTO_INCREMENT PRIMARY KEY,
	Result nvarchar(50) NULL,
	Description nvarchar(MAX) NULL,
	ImgUrl nvarchar(50) NULL,
	ResultChar nchar(1) NULL,
	QuizID BIGINT NULL
);

ALTER TABLE Question ADD FOREIGN KEY (QuizID) REFERENCES Quiz(ID);
ALTER TABLE Answer ADD FOREIGN KEY (QuestionID) REFERENCES Question(ID);
ALTER TABLE Result ADD FOREIGN KEY (QuizID) REFERENCES Quiz(ID);

