CREATE TABLE Quiz(
	ID BIGINT AUTO_INCREMENT PRIMARY KEY,
	NAME nvarchar(50) NULL
);

CREATE TABLE Question(
	ID BIGINT AUTO_INCREMENT PRIMARY KEY,
	QUESTION nvarchar(MAX) NULL,
	QUIZFK BIGINT NOT NULL
);

CREATE TABLE Answer(
	ID BIGINT AUTO_INCREMENT PRIMARY KEY,
	ANSWER nvarchar(MAX) NULL,
	RESULTCHAR nchar(1) NULL,
	QUESTIONFK BIGINT NULL
);

CREATE TABLE Result(
	ID BIGINT AUTO_INCREMENT PRIMARY KEY,
	RESULT nvarchar(50) NULL,
	DESCRIPTION nvarchar(MAX) NULL,
	IMGURL nvarchar(50) NULL,
	RESULTCHAR nchar(1) NULL,
	QUIZFK BIGINT NULL
);

ALTER TABLE Question ADD FOREIGN KEY (QUIZFK) REFERENCES Quiz(ID);
ALTER TABLE Answer ADD FOREIGN KEY (QUESTIONFK) REFERENCES Question(ID);
ALTER TABLE Result ADD FOREIGN KEY (QUIZFK) REFERENCES Quiz(ID);

